stages:
  - build
  - test
  - deploy

variables:
  DEPLOY_PATH: var/www/desafio-devops

build_job:
  stage: build
  image: lportinari/devops-test:1.0.0
  before_script:
    - apt-get update -y && apt-get install gunicorn -y && apt-get install curl -y
    - cd app/
    - gunicorn --log-level debug api:app --daemon
    - sleep 5
    - cd test/
    - chmod +x test.sh && chmod 777 test.sh
   
  script: 
    - ./test.sh > output.txt
    - grep -i SUCCESS output.txt
    - >
      if [ "$?" == "SUCCESS" ]; then
        
      else
        exit 0
      fi
  

test_job:
  stage: test
  needs: ["build_job"]
  image: lportinari/devops-test:1.0.0
  script:
     - apt-get update -y && apt-get install sshpass -y
     - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p32722 root@25.1.14.127 whoami
     - pwd
  dependencies:
     - build_job

