stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: lportinari/devops-test:1.0.0
  script: 
    - docker build -t registry.gitlab.com/desafio-devops .

test_job:
  stage: test
  script:
     - pwd
