stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: lportinari/devops-test:1.0.0
  before_script:
    - cd app/
    - pwd
    
  script: 
    - gunicorn --log-level debug api:app --daemon

test_job:
  stage: test
  script:
     - pwd
  dependencies:
     - build_job

