stages:
  - build
  - test
  - deploy

variables:
  DEPLOY_PATH: var/www/desafio-devops

build_job:
  stage: build
  image: lportinari/devops-test:1.0.0
  before_script:
    - apt-get update -y && apt-get install gunicorn -y
    - cd app/
    - gunicorn --log-level debug api:app --daemon
    - cd test/
    
  script: 
    - sh test.sh

test_job:
  stage: test
  image: lportinari/devops-test:1.0.0
  script:
     - pwd
  dependencies:
     - build_job

