image: docker:19.03.12

stages:
  - build
  - test
  - deploy

variables:
  docker_version: "19.03.12"

services:
  - docker:19.03.12-dind

build_job:
  stage: build
  script: 
    - docker build -t registry.gitlab.com/desafio-devops .

test_job:
  stage: test
  script:
     - docker run registry.gitlab.com/desafio-devops echo TESTADO
